travis:
  secure:
    BINSTAR_TOKEN: A+vkunmMA+12/vCs9n+0dOgqP3qriYOUpyqHxIcFhDiQyO9Lk5C06Oj4Q209iUW8CuPYjyBAf/MJL41qxFrZmwCygyXLVUy0M0BiImcHd9hZALTUU4MxsigVr+urjGOGjnaZxCXco6tRPOIiHY6pAInBmVWH7doZHcVwcbmowtYTXYFu/eqqkUfVXCM+fYdZRkkikKQmiEI2aPEr7jqdYLpmqTFb3hJ2/4qQNlVO7N2KueOjXjsWosSjL5/EFigqNdH8ats3BIWxI6KpyVR6Kkq3pRt/+d/DzNypXtyMheLJCJEskceic5wLJ4Cj34WLch9w9gEJngj+apFEXZ1ELxmEAOmzYC0z6WYs3i1cE1OaBCI4z18AfjSU+l8f2ilozzLcx5RxQRY0dq/B5EtQz2F33kXsu8Hiyi7Lo6l6WlssuYcAPmnlftLGHnX5D1fzGwhgUFrbrLYkFhFyQrh1HdcUQbIXMmub3b5xEQ7MZZVmUsMkoNteS74f+m7EwfOtt3SUgIhwzxLfHBiIlns8MvRxSGthAUvIDJPnlrjKAqvqr+eNZPKYCa63484UFvazdE+jHaWpnLr83Hj0FovChAkZE8hsx5jffvTzEmB0OJwDw1bd7NS5HP/zK7uM8sJ5KVWX0QlIE2b/t97YZSiQeoT5EAQ/3vYq+nDYmQRFZJg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
