travis:
  secure:
    BINSTAR_TOKEN: It6ipiJ89XfOJfS9RRC7pnofB7AtyedutVlL7HcwxFXHuRDbTq3nq13mY1dvZSfhHx2TokByPZyel6DrHnJBD5nv/Ti9W6p9oWk08wF3yVPZLHGgzabOga+1QTABAsORJkkH1SjsH7zkra4jOqX2yM5E/ZuBNTh2hwwG3GrmAbBDnPklzkX3AYACvH1PoEcadV9puT2idhNQOZlS84F98JU9KxGtBrKXW7+SbLndn+BwB/bgND+cYJzXQR8Mop/5rXZzuL+SXmwXCsPpaeLm63CgshfXwGg0Xb2F7p8BqERJo14bR0s6/bhgrkMbXMCCebzXT6UxmqqbG8W6/l5qNv9BH0spPsMqVJGpQJlouSOd1r7suaZ5VIwwacVbcNhm2Z0j9l4tsYoVC41VrA2wsRTHVy/HI8Ix2AtqjFDAKDSfkiHjFbsymg54+ruzbefA4p05QfY7g73sqV7sTBOHyymQCf72QBQJk8N9AF2LIYmsZ5BwUpHNMqd2qPQLbmi4aRnsl8FXLvFFDVuWju04m9dcjcei8DuxV+fj762oCdEA8cuR2BJG+ktkIHHLZ1f2HqJpg0EfsvqmrSf6xPBd47i9/RX+F0IR8yyLD5YUO2UxJGfcjGhr+icqoF0CPUA1r8q5o7gCYoTsiSDdIehcvBLYNB84lBb1k3tsmhytpOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
